# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Lint and Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        container: [ "python:3.8", "python:3.9", "python:3.10", "python:3.11" ]
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache virtualenvironment
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Create and activate Virtualenv
        run: |
          pip install virtualenv
          [ ! -d ".venv" ] && virtualenv .venv
          . .venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run black formatter check
        run: black --check confidence

      - name: Run flake8 formatter check
        run: flake8 confidence

      - name: Run tests with pytest
        run: pytest
